"""Storage contract shared by web and worker, independent of the database."""

from typing import Protocol


class Store(Protocol):
    def create_council(self, visitor_id: str, question: str) -> dict: ...
    def get_council(self, council_id: str) -> dict | None: ...
    def claim_next_council(self, council_id: str | None = None) -> dict | None: ...
    def update_council(self, council_id: str, **fields) -> None: ...
    def list_featured(self) -> list[dict]: ...
    def find_recent_councils(self, since: str) -> list[dict]: ...
    def insert_stories(self, council_id: str, stories: list[dict]) -> None: ...
    def get_stories(self, council_id: str) -> list[dict]: ...
    def upsert_agent(self, council_id: str, agent: dict) -> dict: ...
    def get_agents(self, council_id: str) -> list[dict]: ...
    def insert_turn(self, council_id: str, **fields) -> dict: ...
    def get_turns(self, council_id: str) -> list[dict]: ...
    def insert_evidence(self, council_id: str, **fields) -> dict: ...
    def get_evidence(self, council_id: str) -> list[dict]: ...
    def insert_question(self, council_id: str, **fields) -> dict: ...
    def get_question(self, council_id: str) -> dict | None: ...
    def insert_answer(self, council_id: str, visitor_id: str, answer_id: str) -> dict: ...
    def get_answer(self, council_id: str) -> dict | None: ...
    def insert_verdict(self, council_id: str, **fields) -> dict: ...
    def get_verdict(self, council_id: str) -> dict | None: ...
    def get_profile(self, visitor_id: str) -> dict | None: ...
    def save_profile(self, visitor_id: str, weights: dict, facts: dict) -> None: ...
    def heartbeat(self) -> None: ...
    def get_heartbeat(self) -> str | None: ...
    def cleanup_stale(self, before: str) -> int: ...
    def close(self) -> None: ...
